# Generated by Django 3.2.9 on 2021-12-08 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='employee_details',
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
