# Generated by Django 3.2.9 on 2021-12-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_employee_details_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_details',
            name='phone_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='pincode',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
