# Generated by Django 3.2.9 on 2021-12-08 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_auto_20211208_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_details',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employee_details',
            name='designation',
        ),
    ]
