# Generated by Django 3.2.9 on 2021-12-08 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_auto_20211208_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_details',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employee_details',
            name='country',
        ),
        migrations.RemoveField(
            model_name='employee_details',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='employee_details',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='employee_details',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='employee_details',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='employee_details',
            name='state',
        ),
    ]
