# Generated by Django 3.2.9 on 2021-12-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_auto_20211208_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_details',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee_details',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee_details',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='employee_details',
            name='gender',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee_details',
            name='phone_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='employee_details',
            name='pincode',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='employee_details',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
