# Generated by Django 3.2.9 on 2021-12-14 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0011_auto_20211214_2225'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='member',
            new_name='s_member',
        ),
    ]
