# Generated by Django 3.2.9 on 2021-12-16 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0014_auto_20211216_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chairman',
            name='email',
        ),
        migrations.RemoveField(
            model_name='s_member',
            name='email',
        ),
        migrations.RemoveField(
            model_name='watchman',
            name='email',
        ),
    ]
