# Generated by Django 3.2.9 on 2021-12-22 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0017_auto_20211222_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('flat_no', models.CharField(max_length=50)),
                ('d_t', models.CharField(max_length=50)),
            ],
        ),
    ]
