# Generated by Django 3.2.9 on 2021-12-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0020_auto_20211222_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='time',
            field=models.CharField(max_length=50),
        ),
    ]
