# Generated by Django 3.2.9 on 2021-12-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0022_auto_20211222_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='complain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('flat_no', models.CharField(max_length=10)),
                ('c_subject', models.CharField(max_length=50)),
                ('c_discription', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('flat_no', models.CharField(max_length=10)),
                ('c_subject', models.CharField(max_length=50)),
                ('c_discription', models.CharField(max_length=150)),
            ],
        ),
    ]
