# Generated by Django 3.2.9 on 2021-12-24 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0025_auto_20211223_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sugg_details',
            old_name='c_discription',
            new_name='s_discription',
        ),
        migrations.RenameField(
            model_name='sugg_details',
            old_name='c_subject',
            new_name='s_subject',
        ),
    ]
