# Generated by Django 3.2.9 on 2021-12-28 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0028_alter_user_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_subject', models.CharField(max_length=100)),
                ('n_discription', models.CharField(max_length=250)),
                ('n_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
