# Generated by Django 3.2.9 on 2021-12-28 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0030_rename_notice_notice_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice_details',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
