# Generated by Django 3.2.9 on 2021-12-29 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0031_notice_details_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='event_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(max_length=50)),
                ('e_name', models.CharField(max_length=50)),
                ('e_date', models.CharField(max_length=50)),
                ('e_discription', models.CharField(max_length=50)),
                ('e_category', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
