# Generated by Django 3.2.9 on 2021-12-29 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0032_event_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_details',
            name='e_discription',
        ),
        migrations.AlterField(
            model_name='event_details',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
