# Generated by Django 3.2.9 on 2021-12-29 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0033_auto_20211229_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event_details',
            old_name='e_category',
            new_name='e_discription',
        ),
    ]
